### ISSUE TITLE
Index or tutorial

### ISSUE THREAD

**Issue by maxisimonazzi** [ArmstrongSubero/RP2040#1]
Hi, whats the meaning of P and S starting letter? I think P is for Python pure examples... and S what is for?

S examples have some comments but P dont.

**Comment by ArmstrongSubero** [comment]
Hey there! I'm not done yet, essentially the P projects are yes pure python examples for the Pico, supposed to be completed with nothing more than a few LEDs, and the S are supposed to be System-level projects, interfacing to peripherals and what not...the earlier P projects don't have comments, they were really simple and I didn't realize they needed but now that I have interest I'll definitely add comments!! currently from around the mid-point they do, I'm not done with the repo yet so over the month I'll be adding stuff and completing it....thanks for your support!

**Comment by ArmstrongSubero** [comment]
I'm closing!

**Comment by maxisimonazzi** [comment]
Awesome.... now i see the comments. Do you use some auto comments soft? or IA?

Thanks.

**Comment by ArmstrongSubero** [comment]
Nope comments are all manually written by me lol. Most of these projects I worked on over the years with PIC, Arduino, STM32, Propellor etc etc so now its just a matter of rewriting the logic in Python and updating the descriptions to suit, I'm adding more stuff want to start working on some intermediate and advanced projects...
